[tool.ruff]
# Exclude common directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "migrations",
    "*.pyc",
    ".pytest_cache",
    ".mypy_cache",
    "media",
    "static",
]

# Line length
line-length = 100

# Python version
target-version = "py311"

[tool.ruff.lint]
# Enable rules
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "I",     # isort
    "N",     # pep8-naming
    "UP",    # pyupgrade
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "SIM",   # flake8-simplify
    "ANN",   # type hint
]

# Ignore specific rules
ignore = [
    "E501",  # line too long (handled by formatter)
    "F403",  # unable to detect undefined names from star imports
    "F405",  # name may be undefined, or defined from star imports
    "F811",  # redefinition of unused name
    "B904",  # use raise ... from err in except clause
    "B007",  # loop control variable not used within loop body
    "C901",  # function too complex — souvent inévitable dans les chains/graphs
]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"*/migrations/*.py" = ["ALL"]
"notebooks/*.ipynb" = ["ALL"]

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with tabs
indent-style = "space"

# Like Black, respect magic trailing commas
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending
line-ending = "auto"
